# Limitations and Discussion

The issue of systemic resilience to natural and other hazards is an important
question for transportation agencies in the United States and around the world,
given the precarious situation of many of its transportation assets. Flash
floods, rockfalls, avalanches, earthquakes, and other incidents pose threats to
the network of independent transportation facilities. This research did not
consider risk assessment directly at any level, but rather took as a given that
41 facilities were at some level of risk and played a potentially large systemic
role. A well-conceived approach to systemic resilience should involve all three
elements of resilience: hardening assets from failure through high-quality
engineering and construction; locating maintenance resources in areas where they
can most quickly resolve issues and return facilities to optimal conditions; and
understanding how the system could work effectively in a damaged or degraded
state for medium to long periods of time if necessary.

This research focused on the systemic criticality of 41 facilities that were
assumed to fail independently. Some of the disaster scenarios most likely to
affect highway facilities -- especially a major earthquake -- are likely to
damage multiple highway assets simultaneously. This research might be extended
to consider what would happen if a set of highway facilities failed; is there a
facility that is not critical were it to fail by itself, but ends up being a
critical component of several combinations of failures? Taking the question
further, agencies might consider scenarios where emergency services or
evacuations must operate on a degraded network, an element of the emerging
research area of functional recovery [@zhan2022]. Of course, it is also an open
question as to whether destination and mode choices will follow the same
behavioral patterns in such a scenario.

It is also worth considering that the behavioral response when links in a
highway network are degraded is directly analogous with the behavioral response
when network links are *improved.* As travel model methodologies improve to meet
the challenges posed by induced demand [@thill2005; @volker2020], it would seem
strange to use one methodology for positive network improvements while inventing
wholly new methodologies for negative network improvements.

This research developed a trip-based statewide transportation planning model
using common model design practices including a destination choice trip
distribution model and a complete –-- if rudimentary --– logit-based mode choice
model. Many agencies use a trip-based statewide transportation planning model
with a basic gravity-type trip distribution model and no mode choice component
that cannot be used directly for this kind of analysis. Using logit-based choice
frameworks for trip distribution and mode choice allows the model to incorporate
greater sensitivity to influencing variables and other benefits, in addition to
providing data to support this type of resiliency analysis. The model presented
in this particular research should not be used for infrastructure policy or
forecasting analyses as its parameters have been transferred from three
different source models and not estimated from local data directly. Rather, the
model developed for this research is an illustrative tool, with some degree of
internal consistency and robustness as illustrated by the parameter sensitivity
analysis. Agencies should consider the full range of policies that their models
could evaluate when they make design decisions about how models are structured.

On a related note, only one of the three source models was accompanied with open
documentation describing the estimation of the models along with
goodness of fit and significance statistics. Publishing model estimation reports
--- perhaps even alongside anonymized datasets to allow re-estimation --- would
strengthen the scientific basis of travel forecasting and help earn trust among
the public. This practice would have allowed the sensitivity analysis presented
in this report to be based on draws from the covariance matrix of the individual
parameters rather than an asserted coefficient of variation.

The flexibility and sensitivity afforded by choice models can introduce some
additional challenges, however. The results of the logsum-based choice analysis
highlight one such risk, in that using different cost functions for network
skimming and destination choice can lead to inconsistent model behavior. In this
research and in the USTM highway assignment — and common to many agency modeling
practices — vehicle trips between origins and destinations are loaded onto the
shortest time path, but their destinations are chosen by a combination of travel
time and path distance. Though this issue does not always arise during
calibration and typical volume forecasting efforts, it represents a serious
inconsistency in the travel model framework. Along the same lines, this research
included only a single feedback iteration; understanding how many iterations are
necessary for a travel model to successfully converge -- where the destinations
chosen are no longer changing based on changes to travel times between origins
and destinations -- is an important model design decision that was not explored
here.

A potential limitation in the model developed for this research is that all HBW
trips are flexible in destination choice. This implies that a user could choose
to work in a different place when the path to their previously-chosen work
location is disrupted. This might not be entirely logical for short-term or even
medium-term highway closures, considering that most people will not switch jobs
so quickly. With the recent increase in telecommuting instigated by the COVID-19
pandemic, workplace location is likely even more flexible now than it has been
in the past. This increased flexibility has already called into question how HBW
trips are handled in travel behavior modeling [@salon2021]. A more nuanced
method for estimating HBW trips that accounts for both flexibility and
inflexibility of workplace location might be developed, or the use of
activity-based models that consider journeys to work or telecommuting as a
function of trip distance could be employed.

A similar limitation of this research is that we held the travel times and
levels of service constant for non-highway modes. While some possible incidents
would affect only highways --- such as losing one interstate bridge --- many
would affect adjacent rail transit infrastructure, or would disrupt
non-motorized paths or local transit services which use the highways. Ignoring the  
potential disruption to these modes potentially leads our model to underestimate
the user costs for some scenarios where alternative modes would not be available.

Another limitation in this research surrounds the daily trip assignment
procedure, which introduces two related issues. The first is that the analysis
does not consider incidents which close a facility for a time shorter than 24
hours. Though the target of this research was an understanding of incidents of
longer duration (allowing for a shift in destination choice), the impacts of
shorter incidents on user costs is an important topic. A departure time choice
model might allow users to shift trips to periods with a less compromised
network. Addressing this issue, however, would introduce challenges related to
long-distance trips that would stretch across time periods. A dynamic traffic
assignment or mesoscopic network simulation may be a better strategy to address
this issue [e.g., @kaddoura2018].


Policies that result in a clear and certain outcome are rare, though travel
demand models are sometimes misinterpreted, misused, or even mis-designed to
imply a single policy prediction. Along the same lines, agencies should take a
proactive role in helping travel modelers and transportation planners
incorporate uncertainty in their analysis and convey this uncertainty
responsibly in communications with transportation decision-makers and the
general public. The sensitivity test supplied in this research is a modest step
in this direction.

# Conclusions

The question of systemic resilience of highway assets is an increasing concern
to agencies that must maintain critical infrastructure as it ages in the face of
a changing climate and economy. The basic tools of travel forecasting --- based
on coherent representations of human behavior --- provide compelling tools for
evaluating the criticality of individual highway assets. These tools may require
different expertise than more traditional agency engineers are usually equipped
with, but simplified or simplistic methods can lead to fundamentally different
evaluations of what may happen when the network changes. Specifically, the
results of this analysis suggest travel time based methods may overstate the
excess user costs associated with degraded highway networks, as they do not
consider that travelers might choose different destinations or modes to
accomplish their travel. Demand modelers must first equip their models with the
tools to be useful outside of simple volume forecasting, and then communicate
with their stakeholders and peers the purpose of the model and its powerful
potential for helpful analysis.
