# Acknowledgments {-}

This study was funded by the Utah Department of Transportation. The authors
alone are responsible for the preparation and accuracy of the information, data,
analysis, discussions, recommendations, and conclusions presented herein. The
contents do not necessarily reflect the views, opinions, endorsements, or
policies of the Utah Department of Transportation or the US Department of
Transportation. The Utah Department of Transportation makes no representation or
warranty of any kind, and assumes no liability therefore. Graphics in this document are
made with multiple packages for R [@ggspatial; @modelsummary].

# Data Availability Statement {.unnumbered}

Some or all data, models, or code that support the findings of this study are available from the corresponding author upon reasonable request.

# Author Contribution Statement {.unnumbered}
```{r contrib, results = 'asis', message=FALSE, echo=FALSE}
library(CRediTas)
# crt <- template_create(authors = c("Gregory S. Macfarlane",
#                                    "Max Barnes",
#                                    "Natalie Gray" ))
# fix(crt)
# write_csv(crt, "author_contributions.csv")
crt <- readr::read_csv("author_contributions.csv", show_col_types = FALSE)
```
`r CRediTas::cras_write(crt, markdown = TRUE)`