# Introduction {#intro}

Transportation agencies are tasked with maintaining effective transport networks
connecting a seemingly infinite variety of activities and destinations. These
networks are under constant obvious and non-obvious threats, while the agencies
possess finite resources with which to guard against the threats. Identifying
which facilities in a transportation network are most *critical* --- which would
cause the most disruption if they were to be degraded --- however, is not
trivial. State of the practice techniques typically rely on traffic volumes
represented in terms of vehicles, trips, or freight value [e.g. @aem2020]. But
these methods ignore the fact that some networks have alternate routes readily
available, have multiple well developed modes of transportation, or have
redundant destination locations. When a network link does break, routes, mode
choice, and destination choice often change as well. These responses have been
observed in real-world crisis events like the I-35 W bridge collapse in
Minneapolis and the I-85 bridge fire and collapse in Atlanta [@zhu2010;
@levinson2010; @xie2011; @hamedi2018].

In this research, we apply a destination choice accessibility model to identify
critical highway links in a statewide highway context. This model is designed to
capture the utility lost to individuals operating on a degraded network who may
choose a longer route, a different travel mode, or a different destination. We
then apply the model to a highway network representing the state of Utah. The
model structure permits a more nuanced evaluation of link criticality than using
traffic volume alone or in conjunction with an increased travel time measure.

The paper proceeds as follows. First, a [literature review](#litreview)
discusses previous attempts to identify critical links in transportation
networks. A [methodology](#methodology) section presents the model developed for
this research and describes the implementation process in Utah. A
[results](#results) section describes the model output in detail for one
scenario and then compares and ranks the model outputs for an array of several
dozen independent scenarios. The paper [concludes](#conclusion) with a
discussion of limitations and associated avenues for future research.
