---
title: "Examining the Utility-based Resiliency of Utah's Highway Network"
author:
- name: Gregory Macfarlane
  email: gregmacfarlane@byu.edu
  affiliation: Brigham Young University
- name: Max Barnes
  email: barnesmaxmax@gmail.com
  affiliation: Brigham Young University
- name: Natalie Gray
  email: nat.gray2000@gmail.com
  affiliation: Brigham Young University
date: "`r Sys.Date()`"
address:
- code: Brigham Young University
  address: Brigham Young University, Civil and Environmental Engineering Department, 430 Engineering Building,
    Provo, Utah 84602
footnote:
- code: 1
  text: "Corresponding Author"
site: bookdown::bookdown_site
documentclass: article
journal: Submitted to Journal
bibliography: book.bib
biblio-style: apalike
link-citations: yes
abstract: |
  This is where the abstract should go.
description: A short description
layout: 3p, authoryear
keywords:
- Accessibility
- Passive Data
- Location Choice
---

```{r setup, include = FALSE}
# load R libraries here; the `include` flag in the chunk options above tells
# whether to print the results or not. Usually you don't want to print the
# library statements, or any code on the pdf.

# Main Packages ========
# I use these in every doc
library(tidyverse)
library(knitr)
library(kableExtra)
library(modelsummary)
library(targets)

options(dplyr.summarise.inform = FALSE)

# Other packages ------
# These sometimes get used, and sometimes don't.
library(readxl)
library(leaflet)
library(ggmap)
library(sf)
library(viridis)

# Instructions and options =========
# prints missing data in tables as blank space
options(knitr.kable.NA = '') 
# tells kableExtra to not load latex table packages in the chunk output
options(kableExtra.latex.load_packages = FALSE) 

# round and format numbers that get printed in the text of the article.
inline_hook <- function(x) {
  if (is.numeric(x)) {
    format(x, digits = 3, big.mark = ",")
  } else x
}
knitr::knit_hooks$set(inline = inline_hook)

knitr::opts_chunk$set(echo = TRUE, cache = TRUE)

# options for latex-only output
if(knitr::is_latex_output()) {
  knitr::opts_chunk$set(echo = FALSE, warning = FALSE, message = FALSE)
} 


theme_set(theme_bw())
  
ggmap_bbox <- function(map) {
    if (!inherits(map, "ggmap")) stop("map must be a ggmap object")
    # Extract the bounding box (in lat/lon) from the ggmap to a numeric vector,
    # and set the names to what sf::st_bbox expects:
    map_bbox <- setNames(unlist(attr(map, "bb")),
                         c("ymin", "xmin", "ymax", "xmax"))
    # Coonvert the bbox to an sf polygon, transform it to 3857,
    # and convert back to a bbox (convoluted, but it works)
    bbox_3857 <- st_bbox(st_transform(st_as_sfc(st_bbox(map_bbox, crs = 4326)), 3857))
    # Overwrite the bbox of the ggmap object with the transformed coordinates
    attr(map, "bb")$ll.lat <- bbox_3857["ymin"]
    attr(map, "bb")$ll.lon <- bbox_3857["xmin"]
    attr(map, "bb")$ur.lat <- bbox_3857["ymax"]
    attr(map, "bb")$ur.lon <- bbox_3857["xmax"]
    map
}
```

# Introduction {#intro}

Systemic resiliency is an important consideration for transportation agencies,
though specific definitions of "resiliency" might vary under different contexts.
Some agencies and researchers see resiliency as facility-level design and
engineering that hardens the system against failure [@bradley2007; @peeta2010];
others as an ability for maintenance staff to rapidly restore service following
catastrophe [@zhang2016]; and others as an ability for a system to continue
operating in degraded state [@berdica2002; @ip2011]. Regardless of the
definition used, assessing the resiliency of a transportation network --- and
addressing any potential shortfalls --- requires a method to identify which
links or facilities are most critical to the smooth operation of the network.

Identifying which links in a transportation network are most critical, however, 
is not trivial. State of the practice techniques typically rely on traffic volumes
represented in terms of vehicles, trips, or freight value [@aem2017]. But these 
methods ignore the fact that some networks have alternate routes readily available,
have multiple well developed modes of transportation, or have redundant
destination locations. When a network link does break, routes, mode choice, and
destination choice often change too. These responses have been observed in
real-world crisis events like the I-35 W bridge collapse in Minneapolis and the
I-85 bridge fire and collapse in Atlanta
[@zhu2010; @levinson2010; @xie2011; @hamedi2018].

In this research, we present a model to identify critical highway links using 
destination choice accessibility analysis. This model is designed to capture the
utility lost to individuals operating on a degraded network who may choose 
a longer route, a different travel mode, or a different destination. We then
apply the model to a highway network representing the state of Utah. 
The model structure permits a more nuanced evaluation of link criticality than 
using traffic volume alone or in conjunction with an increased travel time measure.

The paper proceeds as follows. First, a [literature review](#litreview) discusses
previous attempts to analyze the resiliency of transportation networks. A
[methodology](#methodology) section presents the model developed for this
research and describes the implementation process in Utah. A [results](#results) section
describes the model output in detail for one scenario and then compares and ranks
the model outputs for an array of several dozen independent scenarios. The paper
[concludes](#conclusion) with a discussion of limitations and associated avenues 
for future research.

 